const views=["homeView","quizView","resultView","tableView"];
const state={range:"extended",count:20,questions:[],index:0,correct:0,streak:0,bestRun:0,input:"",mistakes:[],locked:false,startedAt:0};
const $=id=>document.getElementById(id);
function show(id){views.forEach(v=>$(v).classList.toggle("active",v===id));window.scrollTo({top:0,behavior:"smooth"})}
function selectGroup(id,key,attr){$(id).addEventListener("click",e=>{const b=e.target.closest("button");if(!b)return;[...$(id).children].forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state[key]=attr==="count"?Number(b.dataset[attr]):b.dataset[attr]})}
selectGroup("rangeOptions","range","range");selectGroup("countOptions","count","count");
function pool(){let nums=state.range==="basic"?[2,3,4,5,6,7,8,9]:state.range==="extended"?[11,12,13,14,15,16,17,18,19]:Array.from({length:18},(_,i)=>i+2);let p=[];nums.forEach(a=>nums.forEach(b=>p.push({a,b,answer:a*b})));for(let i=p.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[p[i],p[j]]=[p[j],p[i]]}return p}
function start(){state.questions=pool().slice(0,state.count);state.index=0;state.correct=0;state.streak=0;state.bestRun=0;state.mistakes=[];state.startedAt=Date.now();show("quizView");loadQuestion()}
function loadQuestion(){state.input="";state.locked=false;const q=state.questions[state.index];$("factorA").textContent=q.a;$("factorB").textContent=q.b;$("answerDisplay").textContent="?";$("answerDisplay").className="answer blank";$("feedback").textContent="数字キーでも入力できます";$("feedback").className="feedback";$("progressText").textContent=`${state.index+1} / ${state.count}`;$("streakText").textContent=`${state.streak}問連続正解`;$("progressBar").style.width=`${state.index/state.count*100}%`}
function inputKey(key){if(state.locked)return;if(key==="clear")state.input=state.input.slice(0,-1);else if(key==="submit"){submit();return}else if(state.input.length<3)state.input+=key;$("answerDisplay").textContent=state.input||"?";$("answerDisplay").classList.toggle("blank",!state.input)}
function submit(){if(!state.input||state.locked)return;state.locked=true;const q=state.questions[state.index],ok=Number(state.input)===q.answer;if(ok){state.correct++;state.streak++;state.bestRun=Math.max(state.bestRun,state.streak);$("feedback").textContent="正解！";$("feedback").className="feedback correct"}else{state.mistakes.push(q);state.streak=0;$("feedback").textContent=`正解は ${q.answer}`;$("feedback").className="feedback wrong"}setTimeout(()=>{state.index++;state.index>=state.count?finish():loadQuestion()},650)}
function finish(){const elapsed=Math.max(1,Math.round((Date.now()-state.startedAt)/1000));const saved=JSON.parse(localStorage.getItem("nineteenRecord")||'{"solved":0,"correct":0,"best":0}');saved.solved+=state.count;saved.correct+=state.correct;saved.best=Math.max(saved.best,state.bestRun);localStorage.setItem("nineteenRecord",JSON.stringify(saved));$("scoreValue").textContent=state.correct;$("scoreTotal").textContent=`/ ${state.count}問`;$("resultAccuracy").textContent=`${Math.round(state.correct/state.count*100)}%`;$("resultTime").textContent=`${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,"0")}`;$("mistakeBox").hidden=!state.mistakes.length;$("mistakeList").innerHTML=state.mistakes.map(q=>`<span>${q.a} × ${q.b} = ${q.answer}</span>`).join("");refreshRecord();show("resultView")}
function refreshRecord(){const r=JSON.parse(localStorage.getItem("nineteenRecord")||'{"solved":0,"correct":0,"best":0}');$("totalSolved").textContent=r.solved;$("bestStreak").textContent=r.best;if(r.solved){$("totalAccuracy").textContent=Math.round(r.correct/r.solved*100);$("accuracyUnit").textContent="%"}else{$("totalAccuracy").textContent="—";$("accuracyUnit").textContent=""}}
function makeTable(){let html="<thead><tr><th>×</th>";for(let i=2;i<=19;i++)html+=`<th>${i}</th>`;html+="</tr></thead><tbody>";for(let a=2;a<=19;a++){html+=`<tr><th>${a}</th>`;for(let b=2;b<=19;b++)html+=`<td>${a*b}</td>`;html+="</tr>"}$("multiplicationTable").innerHTML=html+"</tbody>"}
$("startButton").onclick=start;$("retryButton").onclick=start;$("backButton").onclick=()=>show("homeView");$("homeButton").onclick=()=>show("homeView");$("tableButton").onclick=()=>show("tableView");$("closeTableButton").onclick=()=>show("homeView");$("quitButton").onclick=()=>$("quitDialog").showModal();$("cancelQuit").onclick=()=>$("quitDialog").close();$("confirmQuit").onclick=()=>{$("quitDialog").close();show("homeView")};document.querySelector(".keypad").onclick=e=>{const b=e.target.closest("button");if(b)inputKey(b.dataset.key)};document.addEventListener("keydown",e=>{if(!$("quizView").classList.contains("active"))return;if(/^\d$/.test(e.key))inputKey(e.key);else if(e.key==="Enter")inputKey("submit");else if(e.key==="Backspace")inputKey("clear");else if(e.key==="Escape")$("quitDialog").showModal()});makeTable();refreshRecord();
